--[[
    init.lua
    Created: 12/26/2025 23:20:41
    Description: Autogenerated script file for the map emberfrost_depths.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local emberfrost_depths = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---emberfrost_depths.Init(zone)
--Engine callback function
function emberfrost_depths.Init(zone)


end

---emberfrost_depths.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function emberfrost_depths.EnterSegment(zone, rescuing, segmentID, mapID)
	for member in luanet.each(_DATA.Save.ActiveTeam.Players) do
		local tbl = LTBL(member)
		tbl.EmberfrostRun = true
	end

	-- _DATA.Save.ActiveTeam.Guests:Clear()
	-- print(tostring(Puppeteer.id) .. "ANEMEEMEMEMEM")
	-- RemoveGuestsWithValue(Puppeteer.id)
	-- RemoveGuestsWithValue(TravelingMerchant.id)

	

	if segmentID == 0 and mapID == 0 then

		-- local first_member = GAME:GetPlayerPartyMember(0)
		-- local second_member = GAME:GetPlayerPartyMember(1)

		-- GAME:RemovePlayerTeam(1)

		-- local first_member_tbl = LTBL(first_member)
		-- local second_member_tbl = LTBL(second_member)


		-- first_member_tbl.TeamID = 0
		-- second_member_tbl.TeamID = 1

		-- _DATA.Save.ActiveTeam.Assembly:Add(second_member)
		-- UI:WaitShowDialogue(second_member:GetDisplayName(true) .. " has split off from the team.")
		-- UI:WaitShowDialogue("what the")
	-- elseif segmentID ~= 2 then

		-- print("HRIROOE")
		-- print("Aaaaaaa")

		-- TASK:WaitTask()
		-- GAME:RemovePlayerTeam(0)

		-- GAME:SetTeamLeaderIndex(0)
				-- print("BBbbbbb")
		-- UI:WaitShowDialogue("Bruh")


		-- local key = "emberfrost_team" .. tostring(segmentID)
		


		-- local next_team_id = 1
		-- if segmentID == 1 then
		-- 	next_team_id = 0
		-- end

		-- local next_key = "emberfrost_team" .. tostring(next_team_id)



		-- M_HELPERS.SaveInventory(key)
		-- M_HELPERS.LoadInventory(next_key)


		-- local party_count = GAME:GetPlayerPartyCount()

		-- for i = party_count - 1, 0, -1 do
		-- 	local player = GAME:GetPlayerPartyMember(i)
		-- 	GAME:RemovePlayerTeam(i)
		-- 	GAME:AddPlayerAssembly(player)
		-- end




		-- local assemblyCount = GAME:GetPlayerAssemblyCount()

		-- for i = assemblyCount - 1 - party_count, assemblyCount - 4, -1 do

		-- 	if (i < 0) then
		-- 		break
		-- 	end

		-- 	local member = GAME:GetPlayerAssemblyMember(i)

		-- 	local tbl = LTBL(member)

		-- 	if (tbl.TeamID == next_team_id) then
		-- 		GAME:AddPlayerTeam(member)
		-- 		GAME:RemovePlayerAssembly(i)
		-- 	end
		-- 	print("HIII")




		-- 	local party_count2 = GAME:GetPlayerPartyCount()

		-- for i = party_count2 - 1, 0, -1 do
		-- 	local player = GAME:GetPlayerPartyMember(i)
		-- 	print(tostring(player))
		-- end



		-- 	UI:WaitShowDialogue("TESTING")
	-- end




		-- local player_count = GAME:GetPlayerPartyCount()

		-- for i = 0, player_count - 1, 1 do 
		-- 	local player = GAME:GetPlayerPartyMember(i)
		-- 	local tbl = LTBL(player)
		-- 	tbl.TeamID = nil
		-- end





		-- local third_member = GAME:GetPlayerPartyMember(2)

		-- GAME:RemovePlayerTeam(2)

		-- local third_member_tbl = LTBL(third_member)

		-- third_member_tbl.TeamID = 2

		-- _DATA.Save.ActiveTeam.Assembly:Add(third_member)
		-- UI:WaitShowDialogue(third_member:GetDisplayName(true) .. " has split off from the team.")
	-- elseif segmentID == 2 then

	-- end

	-- UI:ResetSpeaker()
	-- if (player_count ~= 2) then
	-- 	GAME:FadeOut(false, 30)
	-- UI:ResetSpeaker()
	-- l
	
	-- UI:WaitShowDialogue("You need exactly two team members to enter Emberfrost Depths.")
	
		-- TASK:WaitTask(_GAME:EndSegment(RogueEssence.Data.GameProgress.ResultType.Escaped))
		
		-- COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Escaped, 'guildmaster_island', -1, 1, 0)
		-- return
	-- end
	end
end
function CleanUpEmberFrostDepths()
	require 'trios_dungeon_pack.beholder'
	beholder.stopObservingAll()

	local active_enchants = EnchantmentRegistry:GetSelected()
	for _, enchant in pairs(active_enchants) do
		enchant:cleanup()
	end

	SV.EmberFrost.Enchantments.Selected = {}
	SV.EmberFrost.Enchantments.Data = {}
	SV.EmberFrost.CheckpointProgression = 0
	SV.EmberFrost.GotEnchantmentFromCheckpoint = false

	for k, v in pairs(QuestRegistry._registry) do
		v:cleanup()
	end
	for member in luanet.each(_DATA.Save.ActiveTeam.Players) do
		local tbl = LTBL(member)
		tbl.EmberfrostRun = false
	end

	for member in luanet.each(_DATA.Save.ActiveTeam.Assembly) do
		local tbl = LTBL(member)
		tbl.EmberfrostRun = false
	end

	RemoveGuestsWithValue(Puppeteer.id)
	RemoveGuestsWithValue(TravelingMerchant.id)
end

---emberfrost_depths.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function emberfrost_depths.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine

	-- print("Exitiing segment!!!!")
	print(tostring(result))
  PrintInfo("=>> ExitSegment_emberfrost_depths result "..tostring(result).." segment "..tostring(segmentID))

	CleanUpEmberFrostDepths()
  --first check for rescue flag; if we're in rescue mode then take a different path
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
  if exited == true then
    --do nothing
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 0)
  else
		-- segmentID == 0
    if true then
			COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 0)
		else
    --   -- COMMON.UnlockWithFanfare('', true)
    --   COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 0)
    --   -- COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 0)
    -- elseif segmentID == 1 then
    --   -- COMMON.UnlockWithFanfare('', true)
    --   COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Cleared, 'guildmaster_island', -1, 1, 0)
    -- else
      PrintInfo("No exit procedure found!")
      COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 0)
  	end
  end

end

---emberfrost_depths.Rescued(zone, name, mail)
--Engine callback function
function emberfrost_depths.Rescued(zone, name, mail)
  COMMON.Rescued(zone, name, mail)
end

return emberfrost_depths

