--[[
    init.lua
    Created: 10/17/2025 21:27:15
    Description: Autogenerated script file for the map adventurers_peak.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local adventurers_peak = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---adventurers_peak.Init(zone)
--Engine callback function
function adventurers_peak.Init(zone)


end

---adventurers_peak.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function adventurers_peak.EnterSegment(zone, rescuing, segmentID, mapID)


end

---adventurers_peak.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function adventurers_peak.ExitSegment(zone, result, rescue, segmentID, mapID)

  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_champions_road result "..tostring(result).." segment "..tostring(segmentID))
  
  --first check for rescue flag; if we're in rescue mode then take a different path
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
  if exited == true then
    --do nothing
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
  else
    COMMON.EndDungeonDay(result, 'guildmaster_island', -1,8,0)
    -- if segmentID == 0 then
	--   if SV.guildmaster_summit.GameComplete then
    --     COMMON.EndDungeonDay(result, 'guildmaster_island', -1,8,0)
	--   else
	--     SV.guildmaster_summit.ClearedFromTrail = false
	--     GAME:EnterZone('guildmaster_island',-1,8, 0)
	--   end
    -- elseif segmentID == 1 then
    --   COMMON.UnlockWithFanfare('the_sky', true)
    --   COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 4, 2)
    -- else
    --   PrintInfo("No exit procedure found!")
	--   COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    -- end
  end
end


---adventurers_peak.Rescued(zone, name, mail)
--Engine callback function
function adventurers_peak.Rescued(zone, name, mail)
  COMMON.Rescued(zone, name, mail)
end

return adventurers_peak

