--[[
    init.lua
    Created: 12/20/2023 16:26:14
    Description: Autogenerated script file for the map wishmaker_cave.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local wishmaker_cave = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---wishmaker_cave.Init(zone)
--Engine callback function
function wishmaker_cave.Init(zone)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    PrintInfo("=>> Init_wishmaker_cave")
      
end

---wishmaker_cave.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function wishmaker_cave.EnterSegment(zone, rescuing, segmentID, mapID)
  if rescuing ~= true then
    COMMON.BeginDungeon(zone.ID, segmentID, mapID)
  end
end

---wishmaker_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function wishmaker_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_wishmaker_cave result "..tostring(result).." segment "..tostring(segmentID))
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)
  if exited == true then
    -- nothing
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
  else
    -- if segmentID == 0 then
    --   COMMON.UnlockWithFanfare('', true)
    --   COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 0)
    -- elseif segmentID == 1 then
    --   COMMON.UnlockWithFanfare('', true)
    --   COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 0)
    -- else
    --   PrintInfo("No exit procedure found!")
	  COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    -- end
  end

end

---wishmaker_cave.Rescued(zone, name, mail)
--Engine callback function
function wishmaker_cave.Rescued(zone, name, mail)
  COMMON.Rescued(zone, name, mail)
end

return wishmaker_cave

