--[[
    init.lua
    Created: 12/20/2023 16:26:14
    Description: Autogenerated script file for the map wishmaker_cave.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local wishmaker_cave = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---wishmaker_cave.Init(zone)
--Engine callback function
function wishmaker_cave.Init(zone)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    SV.Wishmaker.MadeWish = false
    SV.Wishmaker.BonusScore = 0
    PrintInfo("=>> Init_wishmaker_cave")
      
end

---wishmaker_cave.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function wishmaker_cave.EnterSegment(zone, rescuing, segmentID, mapID)
  if rescuing ~= true then
    COMMON.BeginDungeon(zone.ID, segmentID, mapID)
  end
end

local function ReplaceMoves(chara, move_map)
  for move_idx = 0, 3 do
    local curr_move = chara.BaseSkills[move_idx].SkillNum
    local new_move = move_map[curr_move]
    if new_move ~= nil then
      GAME:SetCharacterSkill(chara, new_move, move_idx)
    end
  end
end

local function ReplaceAbility(chara, ability_map)
  local ability = chara.BaseIntrinsics[0]
  local new_ability = ability_map[ability]
  if new_ability ~= nil then
    chara.BaseIntrinsics[0] = new_ability
  end
end

local function RemoveModdedActions()
  local move_map = {
    thief2 = "thief",
    covet2 = "covet"
  }
  local ability_map = {
    pickpocket2 = "pickpocket"
  }

  local player_count = _DUNGEON.ActiveTeam.Players.Count
  for player_idx = 0, player_count-1, 1 do
    local player = _DUNGEON.ActiveTeam.Players[player_idx]
    ReplaceMoves(player, move_map)
    ReplaceAbility(player, ability_map)
  end
  local assemblyCount = GAME:GetPlayerAssemblyCount()
  for assembly_idx = 0,assemblyCount - 1,1 do
    local player = GAME:GetPlayerAssemblyMember(assembly_idx)
    ReplaceMoves(player, move_map)
    ReplaceAbility(player, ability_map)
  end
end

---wishmaker_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function wishmaker_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_wishmaker_cave result "..tostring(result).." segment "..tostring(segmentID))
  local exited = COMMON.ExitDungeonMissionCheck(result, rescue, zone.ID, segmentID)

  RemoveModdedActions()
  GAME:AddToPlayerMoney(SV.Wishmaker.BonusScore)
  
  if exited == true then
    -- nothing
  elseif result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
    COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Cleared, 'guildmaster_island', -1, 1, 0)
  else
    -- if segmentID == 0 then
    --   COMMON.UnlockWithFanfare('', true)
    --   COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 0)
    -- elseif segmentID == 1 then
    --   COMMON.UnlockWithFanfare('', true)
    --   COMMON.EndDungeonDay(result, 'guildmaster_island', -1, 1, 0)
    -- else
    --   PrintInfo("No exit procedure found!")
    COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Cleared, 'guildmaster_island', -1, 1, 0)
	  -- COMMON.EndDungeonDay(result, SV.checkpoint.Zone, SV.checkpoint.Segment, SV.checkpoint.Map, SV.checkpoint.Entry)
    -- end
  end

  if GAME:InRogueMode() and SV.Wishmaker.RecruitedJirachi then
    GAME:RemoveFromPlayerMoneyBank(75000)
  end
  GAME:RemoveFromPlayerMoney(SV.Wishmaker.BonusScore)
end

---wishmaker_cave.Rescued(zone, name, mail)
--Engine callback function
function wishmaker_cave.Rescued(zone, name, mail)
  COMMON.Rescued(zone, name, mail)
end

return wishmaker_cave

